import { useEffect, useState, useCallback } from "react";
import {
  Box,
  Paper,
  Typography,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  IconButton,
  Button,
  Stack,
  Switch,
  Chip,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  Divider,
  Alert,
  CircularProgress,
  Tooltip,
} from "@mui/material";
import AddIcon from "@mui/icons-material/Add";
import EditIcon from "@mui/icons-material/Edit";
import DeleteIcon from "@mui/icons-material/Delete";
import VolumeUpIcon from "@mui/icons-material/VolumeUp";
import { api } from "@/hooks/useApi";
import type { Configuration, SoundReward } from "@/types/api";

const emptyReward = (): Omit<SoundReward, "id"> => ({
  title: "",
  cost: 100,
  prompt: "Redeem to trigger a sound | Generated by Manao",
  isEnabled: true,
  userInputRequired: false,
  globalCooldown: 0,
  soundFile: null,
});

export function ChannelPointsPage() {
  const [rewards, setRewards] = useState<SoundReward[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editId, setEditId] = useState<string | null>(null);
  const [form, setForm] = useState<Omit<SoundReward, "id">>(emptyReward());
  const [saving, setSaving] = useState(false);

  const load = useCallback(async () => {
    try {
      const config = await api.get<Configuration>("/api/config");
      setRewards(config.soundRewards);
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  const saveAll = async (next: SoundReward[]) => {
    await api.post("/api/config", { soundRewards: next });
    setRewards(next);
  };

  const openCreate = () => {
    setEditId(null);
    setForm(emptyReward());
    setDialogOpen(true);
  };

  const openEdit = (r: SoundReward) => {
    setEditId(r.id);
    setForm({
      title: r.title,
      cost: r.cost,
      prompt: r.prompt,
      isEnabled: r.isEnabled,
      userInputRequired: r.userInputRequired,
      globalCooldown: r.globalCooldown,
      soundFile: r.soundFile,
    });
    setDialogOpen(true);
  };

  const handleSave = async () => {
    try {
      setSaving(true);
      const id =
        editId ??
        crypto.randomUUID?.() ??
        `${Date.now()}-${Math.random().toString(36).slice(2)}`;
      const next = editId
        ? rewards.map((r) => (r.id === editId ? { ...form, id } : r))
        : [...rewards, { ...form, id }];
      await saveAll(next);
      setDialogOpen(false);
    } catch (e) {
      setError(String(e));
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm("Delete this reward?")) return;
    await saveAll(rewards.filter((r) => r.id !== id));
  };

  const toggleEnabled = async (id: string, val: boolean) => {
    const next = rewards.map((r) =>
      r.id === id ? { ...r, isEnabled: val } : r,
    );
    await saveAll(next);
  };

  if (loading)
    return (
      <Box sx={{ display: "flex", justifyContent: "center", pt: 8 }}>
        <CircularProgress />
      </Box>
    );

  return (
    <Box>
      <Stack
        direction="row"
        alignItems="center"
        justifyContent="space-between"
        sx={{ mb: 3 }}
      >
        <Box>
          <Typography variant="h5" fontWeight={700}>
            Channel Points
          </Typography>
          <Typography variant="body2" color="text.secondary">
            Sound rewards redeemable via Twitch Channel Points.
          </Typography>
        </Box>
        <Button
          variant="contained"
          startIcon={<AddIcon />}
          onClick={openCreate}
        >
          Add Reward
        </Button>
      </Stack>

      {error && (
        <Alert severity="error" sx={{ mb: 2 }} onClose={() => setError(null)}>
          {error}
        </Alert>
      )}

      <Paper>
        {rewards.length === 0 ? (
          <Box sx={{ p: 4, textAlign: "center" }}>
            <Typography color="text.secondary">
              No sound rewards yet.
            </Typography>
          </Box>
        ) : (
          <TableContainer>
            <Table size="small">
              <TableHead>
                <TableRow>
                  <TableCell>Enabled</TableCell>
                  <TableCell>Title</TableCell>
                  <TableCell>Cost</TableCell>
                  <TableCell>Cooldown</TableCell>
                  <TableCell>Sound</TableCell>
                  <TableCell align="right">Actions</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {rewards.map((r) => (
                  <TableRow key={r.id} hover>
                    <TableCell>
                      <Switch
                        size="small"
                        checked={r.isEnabled}
                        onChange={(_, v) => toggleEnabled(r.id, v)}
                      />
                    </TableCell>
                    <TableCell>
                      <Typography variant="body2" fontWeight={600}>
                        {r.title}
                      </Typography>
                    </TableCell>
                    <TableCell>
                      <Chip
                        label={r.cost.toLocaleString()}
                        size="small"
                        color="primary"
                        variant="outlined"
                      />
                    </TableCell>
                    <TableCell>
                      <Typography variant="body2" color="text.secondary">
                        {r.globalCooldown}s
                      </Typography>
                    </TableCell>
                    <TableCell>
                      {r.soundFile ? (
                        <Chip
                          icon={<VolumeUpIcon />}
                          label={r.soundFile.split("/").pop()}
                          size="small"
                          color="success"
                          variant="outlined"
                        />
                      ) : (
                        <Typography variant="caption" color="text.disabled">
                          No file
                        </Typography>
                      )}
                    </TableCell>
                    <TableCell align="right">
                      <Tooltip title="Edit">
                        <IconButton size="small" onClick={() => openEdit(r)}>
                          <EditIcon fontSize="small" />
                        </IconButton>
                      </Tooltip>
                      <Tooltip title="Delete">
                        <IconButton
                          size="small"
                          color="error"
                          onClick={() => handleDelete(r.id)}
                        >
                          <DeleteIcon fontSize="small" />
                        </IconButton>
                      </Tooltip>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        )}
      </Paper>

      <Dialog
        open={dialogOpen}
        onClose={() => setDialogOpen(false)}
        maxWidth="sm"
        fullWidth
      >
        <DialogTitle>{editId ? "Edit Reward" : "New Reward"}</DialogTitle>
        <Divider />
        <DialogContent sx={{ pt: 2 }}>
          <Stack spacing={2}>
            <TextField
              size="small"
              fullWidth
              label="Title"
              required
              value={form.title}
              onChange={(e) => setForm({ ...form, title: e.target.value })}
            />
            <TextField
              size="small"
              fullWidth
              label="Cost"
              type="number"
              value={form.cost}
              onChange={(e) =>
                setForm({ ...form, cost: Number(e.target.value) })
              }
              slotProps={{ htmlInput: { min: 0 } }}
            />
            <TextField
              size="small"
              fullWidth
              label="Description/Prompt"
              value={form.prompt}
              onChange={(e) => setForm({ ...form, prompt: e.target.value })}
            />
            <TextField
              size="small"
              fullWidth
              label="Cooldown (seconds)"
              type="number"
              value={form.globalCooldown}
              onChange={(e) =>
                setForm({ ...form, globalCooldown: Number(e.target.value) })
              }
              slotProps={{ htmlInput: { min: 0 } }}
            />
            <TextField
              size="small"
              fullWidth
              label="Sound file path"
              value={form.soundFile ?? ""}
              onChange={(e) =>
                setForm({ ...form, soundFile: e.target.value || null })
              }
              placeholder="./sounds/mySound.mp3"
            />
          </Stack>
        </DialogContent>
        <DialogActions sx={{ p: 2 }}>
          <Button onClick={() => setDialogOpen(false)}>Cancel</Button>
          <Button variant="contained" onClick={handleSave} disabled={saving}>
            {saving ? <CircularProgress size={16} /> : "Save"}
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
}
